#! /usr/bin/python3

import classes
import time

# momma's favourite spaghetti recipe!

separator = '-' * 40 + '\n'

def blackjack():
    game = classes.Game()

    game.display(1)
    while not game.end():
        x = input('Hit? [y/N]\n')
        if x.lower() == 'y' or x == '':
            print(separator)
            print(' ' * (int((len(separator) - len('Player Hit'))/2) - 1) + 'Player Hit\n')
            game.player.player_hit(game.deck)
        elif x.lower() == 'n':
            break
        else:
            print('invalid input')
            continue
        game.display(1)

    if game.end():
        print('You busted!')
        return 0

    print(separator)
    print(' ' * (int((len(separator) - len('Dealer reveals Card'))/2) - 1) + 'Dealer reveals card\n')
    game.display(0)
    while not game.end():
        if game.dealer.score() < 17:
            time.sleep(2.5)
            print(separator)
            print(' ' * (int((len(separator) - len('Dealer Hit'))/2) - 1) + 'Dealer Hit\n')
            game.dealer.player_hit(game.deck)
            game.display(0)
        else:
            break

    if game.end():
        print('Dealer Busted!')
        return 0

    if game.dealer.score() > game.player.score():
        print(' ' * (int((len(separator) - len('You Lost!'))/2) - 1) + 'You Lost!')
    elif game.dealer.score() < game.player.score():
        print(' ' * (int((len(separator) - len('You Won!'))/2) - 1) + 'You won!')
    else:
        print(' ' * (int((len(separator) - len('Draw!'))/2) - 1) + 'Draw!')

    return 0

if __name__ == '__main__':
    while(True):
        print(open('./juice', "r").read())
        blackjack()
        print("\n" + separator)
        x = input('Play again? [y/N]\n')
        if(x.lower() == 'n'):
            break
